### PR TITLE
Adapter by levelDB and couchDB synchronization

### PR DESCRIPTION
**Pull request by jaun-rg**
- Generate path dir
- Registry Collection with LevelDB adapter
- Initialize sync
- Adjust find by all and filters
- Adjust create

### CODE REVIEW

**Comment by millette** [comment]
Thanks for the significant PR. I'm happy if someone finds this adapter useful. I haven't really used it myself much since I started it, and it's my first waterline adapter, so I'm no pro.

I will try and reviews this tonight/tomorrow and merge it. Thanks again :-)

**Comment by millette** [comment]
@jaun-rg Since I haven't used waterline in a few months (no active projects), would you like to take over the maintenance of the npm package?

**Comment by jaun-rg** [comment]
Yes, I can maintenance the npm package for some time

**Comment by millette** [comment]
What's your npm username? I couldn't find it. This way, you'll be able to npm publish this module.

Thanks!

**Comment by jaun-rg** [comment]
my username is : jaun

https://www.npmjs.com/~jaun

**Comment by millette** [comment]
There you go https://www.npmjs.com/package/waterline-pouchdb

Feel free to update the repo links in package.json to point to https://github.com/jaun-rg/waterline-pouchdb - I will update my own readme to point to your project page.

**Comment by jaun-rg** [comment]
Nice.
Thanks!!!

**Pull request closed without merging**
